name: shopping_app
description: "Shopping Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.11.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  auto_route: ^11.1.0
  retrofit: ^4.9.0
  json_annotation: ^4.9.0
  dio: ^5.9.2
  injectable: ^2.7.1+4
  dartz: ^0.10.1
  dartx: ^1.2.0
  equatable: ^2.0.8
  get_it: ^9.2.1
  flutter_svg: ^2.2.4
  shared_preferences: ^2.5.5
  toastification: ^3.0.3
  cached_network_image: ^3.4.1
  i69n: ^3.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0
  build_runner: ^2.6.0
  auto_route_generator: ^10.5.0
  freezed: ^3.2.5
  retrofit_generator: ^10.0.1
  json_serializable: ^6.10.0
  injectable_generator: ^2.12.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist-BlackItalic.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-BoldItalic.ttf
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/Urbanist-ExtraBoldItalic.ttf
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
        - asset: assets/fonts/Urbanist-ExtraLightItalic.ttf
        - asset: assets/fonts/Urbanist-Italic.ttf
        - asset: assets/fonts/Urbanist-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Urbanist-Light.ttf
        - asset: assets/fonts/Urbanist-LightItalic.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist-MediumItalic.ttf
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-SemiBoldItalic.ttf
        - asset: assets/fonts/Urbanist-Thin.ttf
        - asset: assets/fonts/Urbanist-ThinItalic.ttf
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf